In [1]:
print("PREPARANDO EL ENTORNO\n\n")
import os
 # Instalar SDK java 8
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
# Descargar Spark
!wget -q https://archive.apache.org/dist/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz
# Descomprimir la versión de Spark
!tar xf spark-3.3.1-bin-hadoop3.tgz
# Establecer las variables de entorno
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.3.1-bin-hadoop3"
# Descargar findspark
!pip install -q findspark
# Descargar pyspark
!pip install -q pyspark
print("\n\n******** INSTALACIÓN CORRECTA *******")

PREPARANDO EL ENTORNO


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.4/281.4 MB 5.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 KB 21.3 MB/s eta 0:00:00
  Building wheel for pyspark (setup.py) ... done


******** INSTALACIÓN CORRECTA *******

In [2]:
import findspark
findspark.init()

from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [ ]:
df = spark.read.parquet("./data60/")

In [ ]:
df.printSchema()

root
 |-- YEAR: integer (nullable = true)
 |-- MONTH: integer (nullable = true)
 |-- DAY: integer (nullable = true)
 |-- DAY_OF_WEEK: integer (nullable = true)
 |-- AIRLINE: string (nullable = true)
 |-- FLIGHT_NUMBER: integer (nullable = true)
 |-- TAIL_NUMBER: string (nullable = true)
 |-- ORIGIN_AIRPORT: string (nullable = true)
 |-- DESTINATION_AIRPORT: string (nullable = true)
 |-- SCHEDULED_DEPARTURE: integer (nullable = true)
 |-- DEPARTURE_TIME: integer (nullable = true)
 |-- DEPARTURE_DELAY: integer (nullable = true)
 |-- TAXI_OUT: integer (nullable = true)
 |-- WHEELS_OFF: integer (nullable = true)
 |-- SCHEDULED_TIME: integer (nullable = true)
 |-- ELAPSED_TIME: integer (nullable = true)
 |-- AIR_TIME: integer (nullable = true)
 |-- DISTANCE: integer (nullable = true)
 |-- WHEELS_ON: integer (nullable = true)
 |-- TAXI_IN: integer (nullable = true)
 |-- SCHEDULED_ARRIVAL: integer (nullable = true)
 |-- ARRIVAL_TIME: integer (nullable = true)
 |-- ARRIVAL_DELAY: integer (nullable = true)
 |-- DIVERTED: integer (nullable = true)
 |-- CANCELLED: integer (nullable = true)
 |-- CANCELLATION_REASON: string (nullable = true)
 |-- AIR_SYSTEM_DELAY: integer (nullable = true)
 |-- SECURITY_DELAY: integer (nullable = true)
 |-- AIRLINE_DELAY: integer (nullable = true)
 |-- LATE_AIRCRAFT_DELAY: integer (nullable = true)
 |-- WEATHER_DELAY: integer (nullable = true)

In [ ]:
df.show(20, truncate=False)

+----+-----+---+-----------+-------+-------------+-----------+--------------+-------------------+-------------------+--------------+---------------+--------+----------+--------------+------------+--------+--------+---------+-------+-----------------+------------+-------------+--------+---------+-------------------+----------------+--------------+-------------+-------------------+-------------+
|YEAR|MONTH|DAY|DAY_OF_WEEK|AIRLINE|FLIGHT_NUMBER|TAIL_NUMBER|ORIGIN_AIRPORT|DESTINATION_AIRPORT|SCHEDULED_DEPARTURE|DEPARTURE_TIME|DEPARTURE_DELAY|TAXI_OUT|WHEELS_OFF|SCHEDULED_TIME|ELAPSED_TIME|AIR_TIME|DISTANCE|WHEELS_ON|TAXI_IN|SCHEDULED_ARRIVAL|ARRIVAL_TIME|ARRIVAL_DELAY|DIVERTED|CANCELLED|CANCELLATION_REASON|AIR_SYSTEM_DELAY|SECURITY_DELAY|AIRLINE_DELAY|LATE_AIRCRAFT_DELAY|WEATHER_DELAY|
+----+-----+---+-----------+-------+-------------+-----------+--------------+-------------------+-------------------+--------------+---------------+--------+----------+--------------+------------+--------+--------+---------+-------+-----------------+------------+-------------+--------+---------+-------------------+----------------+--------------+-------------+-------------------+-------------+
|2015|1    |1  |4          |AS     |98           |N407AS     |ANC           |SEA                |5                  |2354          |-11            |21      |15        |205           |194         |169     |1448    |404      |4      |430              |408         |-22          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |AA     |2336         |N3KUAA     |LAX           |PBI                |10                 |2             |-8             |12      |14        |280           |279         |263     |2330    |737      |4      |750              |741         |-9           |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |US     |840          |N171US     |SFO           |CLT                |20                 |18            |-2             |16      |34        |286           |293         |266     |2296    |800      |11     |806              |811         |5            |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |AA     |258          |N3HYAA     |LAX           |MIA                |20                 |15            |-5             |15      |30        |285           |281         |258     |2342    |748      |8      |805              |756         |-9           |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |AS     |135          |N527AS     |SEA           |ANC                |25                 |24            |-1             |11      |35        |235           |215         |199     |1448    |254      |5      |320              |259         |-21          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |DL     |806          |N3730B     |SFO           |MSP                |25                 |20            |-5             |18      |38        |217           |230         |206     |1589    |604      |6      |602              |610         |8            |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |NK     |612          |N635NK     |LAS           |MSP                |25                 |19            |-6             |11      |30        |181           |170         |154     |1299    |504      |5      |526              |509         |-17          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |US     |2013         |N584UW     |LAX           |CLT                |30                 |44            |14             |13      |57        |273           |249         |228     |2125    |745      |8      |803              |753         |-10          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |AA     |1112         |N3LAAA     |SFO           |DFW                |30                 |19            |-11            |17      |36        |195           |193         |173     |1464    |529      |3      |545              |532         |-13          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |DL     |1173         |N826DN     |LAS           |ATL                |30                 |33            |3              |12      |45        |221           |203         |186     |1747    |651      |5      |711              |656         |-15          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |DL     |2336         |N958DN     |DEN           |ATL                |30                 |24            |-6             |12      |36        |173           |149         |133     |1199    |449      |4      |523              |453         |-30          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |AA     |1674         |N853AA     |LAS           |MIA                |35                 |27            |-8             |21      |48        |268           |266         |238     |2174    |746      |7      |803              |753         |-10          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |DL     |1434         |N547US     |LAX           |MSP                |35                 |35            |0              |18      |53        |214           |210         |188     |1535    |601      |4      |609              |605         |-4           |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |DL     |2324         |N3751B     |SLC           |ATL                |40                 |34            |-6             |18      |52        |215           |199         |176     |1590    |548      |5      |615              |553         |-22          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |DL     |2440         |N651DL     |SEA           |MSP                |40                 |39            |-1             |28      |107       |189           |198         |166     |1399    |553      |4      |549              |557         |8            |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |AS     |108          |N309AS     |ANC           |SEA                |45                 |41            |-4             |17      |58        |204           |194         |173     |1448    |451      |4      |509              |455         |-14          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |DL     |1560         |N3743H     |ANC           |SEA                |45                 |31            |-14            |25      |56        |210           |200         |171     |1448    |447      |4      |515              |451         |-24          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |UA     |1197         |N78448     |SFO           |IAH                |48                 |42            |-6             |11      |53        |218           |217         |199     |1635    |612      |7      |626              |619         |-7           |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |AS     |122          |N413AS     |ANC           |PDX                |50                 |46            |-4             |11      |57        |215           |201         |187     |1542    |504      |3      |525              |507         |-18          |0       |0        |null               |null            |null          |null         |null               |null         |
|2015|1    |1  |4          |DL     |1670         |N806DN     |PDX           |MSP                |50                 |45            |-5             |9       |54        |193           |186         |171     |1426    |545      |6      |603              |551         |-12          |0       |0        |null               |null            |null          |null         |null               |null         |
+----+-----+---+-----------+-------+-------------+-----------+--------------+-------------------+-------------------+--------------+---------------+--------+----------+--------------+------------+--------+--------+---------+-------+-----------------+------------+-------------+--------+---------+-------------------+----------------+--------------+-------------+-------------------+-------------+
only showing top 20 rows

**Funciones count, countDistinct y aprox_count_distinct**

In [ ]:
df = spark.read.parquet("./data61/dataframes")

In [ ]:
df.printSchema()

root
 |-- nombre: string (nullable = true)
 |-- color: string (nullable = true)
 |-- cantidad: long (nullable = true)

In [ ]:
df.show()

+------+-----+--------+
|nombre|color|cantidad|
+------+-----+--------+
|  Jose| azul|    1900|
|  null| null|    1700|
|  null| rojo|    1300|
|  Juan| rojo|    1500|
+------+-----+--------+

In [ ]:
# count
from pyspark.sql.functions import count

In [ ]:
# Contar la cantidad de filas nombre y color aunque se repitan
df.select(
    count('nombre').alias('conteo_nombre'),
    count('color').alias('conteo_color')
).show()

+-------------+------------+
|conteo_nombre|conteo_color|
+-------------+------------+
|            2|           3|
+-------------+------------+

In [ ]:
df.select(
    count('nombre').alias('conteo_nombre'),
    count('color').alias('conteo_color'),
    count('*').alias('conteo_general')
).show()

+-------------+------------+--------------+
|conteo_nombre|conteo_color|conteo_general|
+-------------+------------+--------------+
|            2|           3|             4|
+-------------+------------+--------------+

In [ ]:
# countDitinct
from pyspark.sql.functions import countDistinct

In [ ]:
# Cuenta las filas color que sean distintas
df.select(
    countDistinct('color').alias('colores_dif')
).show()

+-----------+
|colores_dif|
+-----------+
|          2|
+-----------+

In [ ]:
# approx_count_distinct
from pyspark.sql.functions import approx_count_distinct
dataframe = spark.read.parquet("./data61/vuelos/")

In [ ]:
dataframe.printSchema()

root
 |-- YEAR: integer (nullable = true)
 |-- MONTH: integer (nullable = true)
 |-- DAY: integer (nullable = true)
 |-- DAY_OF_WEEK: integer (nullable = true)
 |-- AIRLINE: string (nullable = true)
 |-- FLIGHT_NUMBER: integer (nullable = true)
 |-- TAIL_NUMBER: string (nullable = true)
 |-- ORIGIN_AIRPORT: string (nullable = true)
 |-- DESTINATION_AIRPORT: string (nullable = true)
 |-- SCHEDULED_DEPARTURE: integer (nullable = true)
 |-- DEPARTURE_TIME: integer (nullable = true)
 |-- DEPARTURE_DELAY: integer (nullable = true)
 |-- TAXI_OUT: integer (nullable = true)
 |-- WHEELS_OFF: integer (nullable = true)
 |-- SCHEDULED_TIME: integer (nullable = true)
 |-- ELAPSED_TIME: integer (nullable = true)
 |-- AIR_TIME: integer (nullable = true)
 |-- DISTANCE: integer (nullable = true)
 |-- WHEELS_ON: integer (nullable = true)
 |-- TAXI_IN: integer (nullable = true)
 |-- SCHEDULED_ARRIVAL: integer (nullable = true)
 |-- ARRIVAL_TIME: integer (nullable = true)
 |-- ARRIVAL_DELAY: integer (nullable = true)
 |-- DIVERTED: integer (nullable = true)
 |-- CANCELLED: integer (nullable = true)
 |-- CANCELLATION_REASON: string (nullable = true)
 |-- AIR_SYSTEM_DELAY: integer (nullable = true)
 |-- SECURITY_DELAY: integer (nullable = true)
 |-- AIRLINE_DELAY: integer (nullable = true)
 |-- LATE_AIRCRAFT_DELAY: integer (nullable = true)
 |-- WEATHER_DELAY: integer (nullable = true)

In [ ]:
dataframe.select(
    countDistinct('AIRLINE'),
    approx_count_distinct('AIRLINE')
).show()

+-----------------------+------------------------------+
|count(DISTINCT AIRLINE)|approx_count_distinct(AIRLINE)|
+-----------------------+------------------------------+
|                     14|                            13|
+-----------------------+------------------------------+

**Función min y max**

In [ ]:
vuelos = spark.read.parquet("./data62/")

In [ ]:
vuelos.printSchema()

root
 |-- YEAR: integer (nullable = true)
 |-- MONTH: integer (nullable = true)
 |-- DAY: integer (nullable = true)
 |-- DAY_OF_WEEK: integer (nullable = true)
 |-- AIRLINE: string (nullable = true)
 |-- FLIGHT_NUMBER: integer (nullable = true)
 |-- TAIL_NUMBER: string (nullable = true)
 |-- ORIGIN_AIRPORT: string (nullable = true)
 |-- DESTINATION_AIRPORT: string (nullable = true)
 |-- SCHEDULED_DEPARTURE: integer (nullable = true)
 |-- DEPARTURE_TIME: integer (nullable = true)
 |-- DEPARTURE_DELAY: integer (nullable = true)
 |-- TAXI_OUT: integer (nullable = true)
 |-- WHEELS_OFF: integer (nullable = true)
 |-- SCHEDULED_TIME: integer (nullable = true)
 |-- ELAPSED_TIME: integer (nullable = true)
 |-- AIR_TIME: integer (nullable = true)
 |-- DISTANCE: integer (nullable = true)
 |-- WHEELS_ON: integer (nullable = true)
 |-- TAXI_IN: integer (nullable = true)
 |-- SCHEDULED_ARRIVAL: integer (nullable = true)
 |-- ARRIVAL_TIME: integer (nullable = true)
 |-- ARRIVAL_DELAY: integer (nullable = true)
 |-- DIVERTED: integer (nullable = true)
 |-- CANCELLED: integer (nullable = true)
 |-- CANCELLATION_REASON: string (nullable = true)
 |-- AIR_SYSTEM_DELAY: integer (nullable = true)
 |-- SECURITY_DELAY: integer (nullable = true)
 |-- AIRLINE_DELAY: integer (nullable = true)
 |-- LATE_AIRCRAFT_DELAY: integer (nullable = true)
 |-- WEATHER_DELAY: integer (nullable = true)

In [ ]:
from pyspark.sql.functions import min, max, col

In [ ]:
vuelos.select(
    min('AIR_TIME').alias('menor_tiempo'),
    max('AIR_TIME').alias('mayor_tiempo')
).show()

+------------+------------+
|menor_tiempo|mayor_tiempo|
+------------+------------+
|           7|         690|
+------------+------------+

In [ ]:
vuelos.select(
    min('AIRLINE_DELAY'),
    max('AIRLINE_DELAY')
).show()

+------------------+------------------+
|min(AIRLINE_DELAY)|max(AIRLINE_DELAY)|
+------------------+------------------+
|                 0|              1971|
+------------------+------------------+

**Funciones sum, sumDistinct y avg**

In [ ]:
vuelos = spark.read.parquet("./data63/")

In [ ]:
from pyspark.sql.functions import sum, sumDistinct, avg, count, sum_distinct

In [ ]:
# sum
vuelos.printSchema()

root
 |-- YEAR: integer (nullable = true)
 |-- MONTH: integer (nullable = true)
 |-- DAY: integer (nullable = true)
 |-- DAY_OF_WEEK: integer (nullable = true)
 |-- AIRLINE: string (nullable = true)
 |-- FLIGHT_NUMBER: integer (nullable = true)
 |-- TAIL_NUMBER: string (nullable = true)
 |-- ORIGIN_AIRPORT: string (nullable = true)
 |-- DESTINATION_AIRPORT: string (nullable = true)
 |-- SCHEDULED_DEPARTURE: integer (nullable = true)
 |-- DEPARTURE_TIME: integer (nullable = true)
 |-- DEPARTURE_DELAY: integer (nullable = true)
 |-- TAXI_OUT: integer (nullable = true)
 |-- WHEELS_OFF: integer (nullable = true)
 |-- SCHEDULED_TIME: integer (nullable = true)
 |-- ELAPSED_TIME: integer (nullable = true)
 |-- AIR_TIME: integer (nullable = true)
 |-- DISTANCE: integer (nullable = true)
 |-- WHEELS_ON: integer (nullable = true)
 |-- TAXI_IN: integer (nullable = true)
 |-- SCHEDULED_ARRIVAL: integer (nullable = true)
 |-- ARRIVAL_TIME: integer (nullable = true)
 |-- ARRIVAL_DELAY: integer (nullable = true)
 |-- DIVERTED: integer (nullable = true)
 |-- CANCELLED: integer (nullable = true)
 |-- CANCELLATION_REASON: string (nullable = true)
 |-- AIR_SYSTEM_DELAY: integer (nullable = true)
 |-- SECURITY_DELAY: integer (nullable = true)
 |-- AIRLINE_DELAY: integer (nullable = true)
 |-- LATE_AIRCRAFT_DELAY: integer (nullable = true)
 |-- WEATHER_DELAY: integer (nullable = true)

In [ ]:
# suma de la distancia
vuelos.select(
    sum('DISTANCE').alias('sum_dis')
).show()

+----------+
|   sum_dis|
+----------+
|4785357409|
+----------+

In [ ]:
# suma de la distancias diferentes
vuelos.select(
    sum_distinct('DISTANCE').alias('sum_dis_dif')
).show()

+-----------+
|sum_dis_dif|
+-----------+
|    1442300|
+-----------+

In [ ]:
# avg - calcula el promedio
vuelos.select(
    avg('AIR_TIME').alias('promedio_aire'),
    (sum('AIR_TIME') / count('AIR_TIME')).alias('prom_manual')
).show()

+------------------+------------------+
|     promedio_aire|       prom_manual|
+------------------+------------------+
|113.51162809012519|113.51162809012519|
+------------------+------------------+

**Agregación con agrupación**

In [ ]:
vuelos = spark.read.parquet("./data64/")
vuelos.printSchema()

root
 |-- YEAR: integer (nullable = true)
 |-- MONTH: integer (nullable = true)
 |-- DAY: integer (nullable = true)
 |-- DAY_OF_WEEK: integer (nullable = true)
 |-- AIRLINE: string (nullable = true)
 |-- FLIGHT_NUMBER: integer (nullable = true)
 |-- TAIL_NUMBER: string (nullable = true)
 |-- ORIGIN_AIRPORT: string (nullable = true)
 |-- DESTINATION_AIRPORT: string (nullable = true)
 |-- SCHEDULED_DEPARTURE: integer (nullable = true)
 |-- DEPARTURE_TIME: integer (nullable = true)
 |-- DEPARTURE_DELAY: integer (nullable = true)
 |-- TAXI_OUT: integer (nullable = true)
 |-- WHEELS_OFF: integer (nullable = true)
 |-- SCHEDULED_TIME: integer (nullable = true)
 |-- ELAPSED_TIME: integer (nullable = true)
 |-- AIR_TIME: integer (nullable = true)
 |-- DISTANCE: integer (nullable = true)
 |-- WHEELS_ON: integer (nullable = true)
 |-- TAXI_IN: integer (nullable = true)
 |-- SCHEDULED_ARRIVAL: integer (nullable = true)
 |-- ARRIVAL_TIME: integer (nullable = true)
 |-- ARRIVAL_DELAY: integer (nullable = true)
 |-- DIVERTED: integer (nullable = true)
 |-- CANCELLED: integer (nullable = true)
 |-- CANCELLATION_REASON: string (nullable = true)
 |-- AIR_SYSTEM_DELAY: integer (nullable = true)
 |-- SECURITY_DELAY: integer (nullable = true)
 |-- AIRLINE_DELAY: integer (nullable = true)
 |-- LATE_AIRCRAFT_DELAY: integer (nullable = true)
 |-- WEATHER_DELAY: integer (nullable = true)

In [ ]:
from pyspark.sql.functions import desc

In [ ]:
# Agrupamos por el aeropuerto de origen, contar cuantos vuelos hay desde el aeropuerto
# de origen y ordenarlo descendiente
(vuelos.groupBy('ORIGIN_AIRPORT')
    .count()
    .orderBy(desc('count'))
).show()

+--------------+------+
|ORIGIN_AIRPORT| count|
+--------------+------+
|           ATL|346836|
|           ORD|285884|
|           DFW|239551|
|           DEN|196055|
|           LAX|194673|
|           SFO|148008|
|           PHX|146815|
|           IAH|146622|
|           LAS|133181|
|           MSP|112117|
|           MCO|110982|
|           SEA|110899|
|           DTW|108500|
|           BOS|107847|
|           EWR|101772|
|           CLT|100324|
|           LGA| 99605|
|           SLC| 97210|
|           JFK| 93811|
|           BWI| 86079|
+--------------+------+
only showing top 20 rows

In [ ]:
# Los mismo pero le agregamos el aeropuerto de destino
(vuelos.groupBy('ORIGIN_AIRPORT', 'DESTINATION_AIRPORT')
    .count()
    .orderBy(desc('count'))
).show()

+--------------+-------------------+-----+
|ORIGIN_AIRPORT|DESTINATION_AIRPORT|count|
+--------------+-------------------+-----+
|           SFO|                LAX|13744|
|           LAX|                SFO|13457|
|           JFK|                LAX|12016|
|           LAX|                JFK|12015|
|           LAS|                LAX| 9715|
|           LGA|                ORD| 9639|
|           LAX|                LAS| 9594|
|           ORD|                LGA| 9575|
|           SFO|                JFK| 8440|
|           JFK|                SFO| 8437|
|           OGG|                HNL| 8313|
|           HNL|                OGG| 8282|
|           LAX|                ORD| 8256|
|           ATL|                LGA| 8234|
|           LGA|                ATL| 8215|
|           ATL|                MCO| 8202|
|           MCO|                ATL| 8202|
|           SFO|                LAS| 7995|
|           ORD|                LAX| 7941|
|           LAS|                SFO| 7870|
+--------------+-------------------+-----+
only showing top 20 rows

**Varias agregaciones por grupo**

In [ ]:
vuelos = spark.read.parquet("./data65/")

In [ ]:
vuelos.groupBy('ORIGIN_AIRPORT').agg(
    count('AIR_TIME').alias('tiempo_aire'),
    min('AIR_TIME').alias('min'),
    max('AIR_TIME').alias('max')
).orderBy(desc('tiempo_aire')).show()

+--------------+-----------+---+---+
|ORIGIN_AIRPORT|tiempo_aire|min|max|
+--------------+-----------+---+---+
|           ATL|     343506| 15|614|
|           ORD|     276554| 13|571|
|           DFW|     232647| 11|534|
|           DEN|     193402| 12|493|
|           LAX|     192003| 14|409|
|           PHX|     145552| 19|444|
|           SFO|     145491|  8|389|
|           IAH|     144019| 15|524|
|           LAS|     131937| 25|429|
|           MSP|     111055| 14|537|
|           SEA|     110178| 17|412|
|           MCO|     109532| 25|395|
|           DTW|     106992| 15|341|
|           BOS|     104804| 16|432|
|           CLT|      99052| 17|379|
|           EWR|      98341| 21|683|
|           SLC|      96505| 18|419|
|           LGA|      94834| 19|311|
|           JFK|      91663| 29|690|
|           BWI|      84329| 19|398|
+--------------+-----------+---+---+
only showing top 20 rows

In [ ]:
vuelos.groupBy('MONTH').agg(
    count('ARRIVAL_DELAY').alias('conteo_de_retrasos'),
    avg('DISTANCE').alias('prom_dist')
).orderBy(desc('conteo_de_retrasos')).show()

+-----+------------------+-----------------+
|MONTH|conteo_de_retrasos|        prom_dist|
+-----+------------------+-----------------+
|    7|            514384|841.4772794487611|
|    8|            503956|834.8244276603413|
|    6|            492847|835.6302716626612|
|    3|            492138|816.0553268611494|
|    5|            489641|823.3230588760807|
|   10|            482878|816.4436127652134|
|    4|            479251|817.0060476016745|
|   12|            469717|837.8018926194103|
|   11|            462367|820.2482434846529|
|    9|            462153|815.8487523282274|
|    1|            457013|803.2612794913696|
|    2|            407663| 800.785449834689|
+-----+------------------+-----------------+

**Agregación con pivote**

In [ ]:
estudiantes = spark.read.parquet("./data66/")

In [ ]:
estudiantes.show()

+------+----+----+----------+
|nombre|sexo|peso|graduacion|
+------+----+----+----------+
|  Jose|   M|  80|      2000|
| Hilda|   F|  50|      2000|
|  Juan|   M|  75|      2000|
| Pedro|   M|  76|      2001|
|Katia+|   F|  65|      2001|
+------+----+----+----------+

In [ ]:
from pyspark.sql.functions import min, max, avg, col

In [ ]:
# Promedio por año de graduación
estudiantes.groupBy('graduacion').pivot('sexo').agg(avg('peso'), min('peso'), max('peso')).show()

+----------+-----------+-----------+-----------+-----------+-----------+-----------+
|graduacion|F_avg(peso)|F_min(peso)|F_max(peso)|M_avg(peso)|M_min(peso)|M_max(peso)|
+----------+-----------+-----------+-----------+-----------+-----------+-----------+
|      2001|       65.0|         65|         65|       76.0|         76|         76|
|      2000|       50.0|         50|         50|       77.5|         75|         80|
+----------+-----------+-----------+-----------+-----------+-----------+-----------+

In [ ]:
# Lo mismo, pero con el peso mínimo y máximo
estudiantes.groupBy('graduacion').pivot('sexo').agg(avg('peso')).show()

+----------+----+----+
|graduacion|   F|   M|
+----------+----+----+
|      2001|65.0|76.0|
|      2000|50.0|77.5|
+----------+----+----+

In [ ]:
# Lo mismo, pero solo hombres
estudiantes.groupBy('graduacion').pivot('sexo', ['M']).agg(avg('peso'), min('peso'), max('peso')).show()

+----------+-----------+-----------+-----------+
|graduacion|M_avg(peso)|M_min(peso)|M_max(peso)|
+----------+-----------+-----------+-----------+
|      2001|       76.0|         76|         76|
|      2000|       77.5|         75|         80|
+----------+-----------+-----------+-----------+

In [ ]:
# Lo mismo, pero solo mujeres
estudiantes.groupBy('graduacion').pivot('sexo', ['F']).agg(avg('peso'), min('peso'), max('peso')).show()

+----------+-----------+-----------+-----------+
|graduacion|F_avg(peso)|F_min(peso)|F_max(peso)|
+----------+-----------+-----------+-----------+
|      2001|       65.0|         65|         65|
|      2000|       50.0|         50|         50|
+----------+-----------+-----------+-----------+

**Inner Join**

In [12]:
# El conjunto despues del JOIN contendra filas solo cuando la expresión se evalue como verdadera,
# es decir, cuando los valores de las columnas sean los mismos en ambos conjuntos.

In [3]:
empleados = spark.read.parquet("./data69/empleados/")
departamentos = spark.read.parquet("./data69/departamentos/")

In [4]:
empleados.show()

+------+--------+
|nombre|num_dpto|
+------+--------+
|  Luis|      33|
| Katia|      33|
|  Raul|      34|
| Pedro|       0|
| Laura|      34|
|Sandro|      31|
+------+--------+

In [5]:
departamentos.show()

+---+-----------+
| id|nombre_dpto|
+---+-----------+
| 31|     letras|
| 33|    derecho|
| 34| matemática|
| 35|informática|
+---+-----------+

In [7]:
from pyspark.sql.functions import col
join_df = empleados.join(departamentos, col('num_dpto') == col('id'))
join_df.show()

+------+--------+---+-----------+
|nombre|num_dpto| id|nombre_dpto|
+------+--------+---+-----------+
|  Luis|      33| 33|    derecho|
| Katia|      33| 33|    derecho|
|  Raul|      34| 34| matemática|
| Laura|      34| 34| matemática|
|Sandro|      31| 31|     letras|
+------+--------+---+-----------+

In [8]:
# otra forma
join_df = empleados.join(departamentos, col('num_dpto') == col('id'), 'inner')
join_df.show()

+------+--------+---+-----------+
|nombre|num_dpto| id|nombre_dpto|
+------+--------+---+-----------+
|  Luis|      33| 33|    derecho|
| Katia|      33| 33|    derecho|
|  Raul|      34| 34| matemática|
| Laura|      34| 34| matemática|
|Sandro|      31| 31|     letras|
+------+--------+---+-----------+

In [9]:
# otra forma
join_df = empleados.join(departamentos).where(col('num_dpto') == col('id'))
join_df.show()

+------+--------+---+-----------+
|nombre|num_dpto| id|nombre_dpto|
+------+--------+---+-----------+
|  Luis|      33| 33|    derecho|
| Katia|      33| 33|    derecho|
|  Raul|      34| 34| matemática|
| Laura|      34| 34| matemática|
|Sandro|      31| 31|     letras|
+------+--------+---+-----------+

**Left Outer Join**

In [13]:
# Contiene todos los elementos del dataframe de la izquierda. Y llena con nulo los de la derecha que no se encuentran.

In [14]:
empleados = spark.read.parquet("./data70/empleados/")
departamentos = spark.read.parquet("./data70/departamentos/")

In [15]:
from pyspark.sql.functions import col

In [16]:
empleados.join(departamentos, col('num_dpto') == col('id'), 'leftouter').show()

+------+--------+----+-----------+
|nombre|num_dpto|  id|nombre_dpto|
+------+--------+----+-----------+
|  Luis|      33|  33|    derecho|
| Katia|      33|  33|    derecho|
|  Raul|      34|  34| matemática|
| Pedro|       0|null|       null|
| Laura|      34|  34| matemática|
|Sandro|      31|  31|     letras|
+------+--------+----+-----------+

In [17]:
# otra forma
empleados.join(departamentos, col('num_dpto') == col('id'), 'left_outer').show()

+------+--------+----+-----------+
|nombre|num_dpto|  id|nombre_dpto|
+------+--------+----+-----------+
|  Luis|      33|  33|    derecho|
| Katia|      33|  33|    derecho|
|  Raul|      34|  34| matemática|
| Pedro|       0|null|       null|
| Laura|      34|  34| matemática|
|Sandro|      31|  31|     letras|
+------+--------+----+-----------+

In [18]:
# otra forma]
empleados.join(departamentos, col('num_dpto') == col('id'), 'left').show()

+------+--------+----+-----------+
|nombre|num_dpto|  id|nombre_dpto|
+------+--------+----+-----------+
|  Luis|      33|  33|    derecho|
| Katia|      33|  33|    derecho|
|  Raul|      34|  34| matemática|
| Pedro|       0|null|       null|
| Laura|      34|  34| matemática|
|Sandro|      31|  31|     letras|
+------+--------+----+-----------+

**Right Outer Join**

In [19]:
# Contiene todos los elementos del dataframe de la derecha. Y llena con nulo los de la izquierda que no se encuentran.

In [20]:
from pyspark.sql.functions import col

In [21]:
empleados.join(departamentos, col('num_dpto') == col('id'), 'rightouter').show()

+------+--------+---+-----------+
|nombre|num_dpto| id|nombre_dpto|
+------+--------+---+-----------+
|Sandro|      31| 31|     letras|
| Katia|      33| 33|    derecho|
|  Luis|      33| 33|    derecho|
| Laura|      34| 34| matemática|
|  Raul|      34| 34| matemática|
|  null|    null| 35|informática|
+------+--------+---+-----------+

In [22]:
# otra forma
empleados.join(departamentos, col('num_dpto') == col('id'), 'right_outer').show()

+------+--------+---+-----------+
|nombre|num_dpto| id|nombre_dpto|
+------+--------+---+-----------+
|Sandro|      31| 31|     letras|
| Katia|      33| 33|    derecho|
|  Luis|      33| 33|    derecho|
| Laura|      34| 34| matemática|
|  Raul|      34| 34| matemática|
|  null|    null| 35|informática|
+------+--------+---+-----------+

In [23]:
# otra forma
empleados.join(departamentos, col('num_dpto') == col('id'), 'right').show()

+------+--------+---+-----------+
|nombre|num_dpto| id|nombre_dpto|
+------+--------+---+-----------+
|Sandro|      31| 31|     letras|
| Katia|      33| 33|    derecho|
|  Luis|      33| 33|    derecho|
| Laura|      34| 34| matemática|
|  Raul|      34| 34| matemática|
|  null|    null| 35|informática|
+------+--------+---+-----------+

**Full Outer Join**

In [24]:
# Combina todo.

In [28]:
from pyspark.sql.functions import col

In [29]:
empleados.join(departamentos, col('num_dpto') == col('id'), 'outer').show()

+------+--------+----+-----------+
|nombre|num_dpto|  id|nombre_dpto|
+------+--------+----+-----------+
| Pedro|       0|null|       null|
|Sandro|      31|  31|     letras|
|  Luis|      33|  33|    derecho|
| Katia|      33|  33|    derecho|
|  Raul|      34|  34| matemática|
| Laura|      34|  34| matemática|
|  null|    null|  35|informática|
+------+--------+----+-----------+

**Left Anti Join**

In [30]:
# Busca que filas del conjunto de datos de la izquierda no tiene filas coincidentes en el conjunto de datos de la derecha.

In [31]:
from pyspark.sql.functions import col

In [32]:
empleados.join(departamentos, col('num_dpto') == col('id'), 'left_anti').show()

+------+--------+
|nombre|num_dpto|
+------+--------+
| Pedro|       0|
+------+--------+

In [33]:
departamentos.join(empleados, col('num_dpto') == col('id'), 'left_anti').show()

+---+-----------+
| id|nombre_dpto|
+---+-----------+
| 35|informática|
+---+-----------+

**Left Semi Join**

In [34]:
# Igual al inner join, pero el resultado no incluye las columnas del conjunto de la derecha. Contiene solo 
# las filas coincidentes.

In [35]:
from pyspark.sql.functions import col

In [36]:
empleados.join(departamentos, col('num_dpto') == col('id'), 'left_semi').show()

+------+--------+
|nombre|num_dpto|
+------+--------+
|  Luis|      33|
| Katia|      33|
|  Raul|      34|
| Laura|      34|
|Sandro|      31|
+------+--------+

**Cross Join**

In [37]:
# Une cada fila del conjunto de datos de la izquierda con el conjunto de datos de la derecha.

In [38]:
df = empleados.crossJoin(departamentos)

In [39]:
df.show()

+------+--------+---+-----------+
|nombre|num_dpto| id|nombre_dpto|
+------+--------+---+-----------+
|  Luis|      33| 31|     letras|
|  Luis|      33| 33|    derecho|
|  Luis|      33| 34| matemática|
|  Luis|      33| 35|informática|
| Katia|      33| 31|     letras|
| Katia|      33| 33|    derecho|
| Katia|      33| 34| matemática|
| Katia|      33| 35|informática|
|  Raul|      34| 31|     letras|
|  Raul|      34| 33|    derecho|
|  Raul|      34| 34| matemática|
|  Raul|      34| 35|informática|
| Pedro|       0| 31|     letras|
| Pedro|       0| 33|    derecho|
| Pedro|       0| 34| matemática|
| Pedro|       0| 35|informática|
| Laura|      34| 31|     letras|
| Laura|      34| 33|    derecho|
| Laura|      34| 34| matemática|
| Laura|      34| 35|informática|
+------+--------+---+-----------+
only showing top 20 rows

**Manejo de nombres de columnas duplicados**

In [40]:
from pyspark.sql.functions import col

In [48]:
depa = departamentos.withColumn('num_dpto', col('id'))

In [49]:
depa.printSchema()
empleados.printSchema()

root
 |-- id: long (nullable = true)
 |-- nombre_dpto: string (nullable = true)
 |-- num_dpto: long (nullable = true)

root
 |-- nombre: string (nullable = true)
 |-- num_dpto: long (nullable = true)

In [51]:
# Para columnas con nombre similar o ambiguas
df_con_duplicados = empleados.join(depa, empleados['num_dpto'] == depa['num_dpto'])
df_con_duplicados.show()

+------+--------+---+-----------+--------+
|nombre|num_dpto| id|nombre_dpto|num_dpto|
+------+--------+---+-----------+--------+
|Sandro|      31| 31|     letras|      31|
| Katia|      33| 33|    derecho|      33|
|  Luis|      33| 33|    derecho|      33|
| Laura|      34| 34| matemática|      34|
|  Raul|      34| 34| matemática|      34|
+------+--------+---+-----------+--------+

In [52]:
df_con_duplicados.printSchema()

root
 |-- nombre: string (nullable = true)
 |-- num_dpto: long (nullable = true)
 |-- id: long (nullable = true)
 |-- nombre_dpto: string (nullable = true)
 |-- num_dpto: long (nullable = true)

In [53]:
df_con_duplicados.select(empleados['num_dpto']).show()

+--------+
|num_dpto|
+--------+
|      33|
|      33|
|      34|
|      34|
|      31|
+--------+

**Shuffle Hash Join y Broadcast Hash Join**

In [54]:
# Cuando el tamaño de ambos conjuntos de datos es grande, se utiliza Shuffle Hash Join.

In [55]:
from pyspark.sql.functions import broadcast, col
empleados.join(broadcast(departamentos), col('num_dpto') == col('id')).show()

+------+--------+---+-----------+
|nombre|num_dpto| id|nombre_dpto|
+------+--------+---+-----------+
|  Luis|      33| 33|    derecho|
| Katia|      33| 33|    derecho|
|  Raul|      34| 34| matemática|
| Laura|      34| 34| matemática|
|Sandro|      31| 31|     letras|
+------+--------+---+-----------+

In [57]:
# Plan de ejecución
empleados.join(broadcast(departamentos), col('num_dpto') == col('id')).explain()

== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- BroadcastHashJoin [num_dpto#100L], [id#103L], Inner, BuildRight, false
   :- Filter isnotnull(num_dpto#100L)
   :  +- FileScan parquet [nombre#99,num_dpto#100L] Batched: true, DataFilters: [isnotnull(num_dpto#100L)], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/content/data70/empleados], PartitionFilters: [], PushedFilters: [IsNotNull(num_dpto)], ReadSchema: struct<nombre:string,num_dpto:bigint>
   +- BroadcastExchange HashedRelationBroadcastMode(List(input[0, bigint, false]),false), [plan_id=1606]
      +- Filter isnotnull(id#103L)
         +- FileScan parquet [id#103L,nombre_dpto#104] Batched: true, DataFilters: [isnotnull(id#103L)], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/content/data70/departamentos], PartitionFilters: [], PushedFilters: [IsNotNull(id)], ReadSchema: struct<id:bigint,nombre_dpto:string>

**Ejercicios**

Los datos adjuntos a esta lección forman parte de la base de datos Football Data from Transfermarkt de Kaggle. El conjunto de datos se compone de varios archivos CSV con información sobre competiciones, juegos, clubes, jugadores y apariciones.

In [93]:
from pyspark.sql.functions import col, desc, count_distinct, count

In [161]:
juegos = spark.read.option('header', 'true').option('inferSchema', 'true').csv("./ejercicios/games.csv")
clubes = spark.read.option('header', 'true').option('inferSchema', 'true').csv("./ejercicios/clubs.csv")
jugadores = spark.read.option('header', 'true').option('inferSchema', 'true').csv("./ejercicios/players.csv")
apariciones = spark.read.option('header', 'true').option('inferSchema', 'true').csv("./ejercicios/appearances.csv")
liga = spark.read.option('header', 'true').option('inferSchema', 'true').csv("./ejercicios/leagues.csv")
competiciones = spark.read.option('header', 'true').option('inferSchema', 'true').csv("./ejercicios/competitions.csv")

In [64]:
juegos.show(5, truncate=False)

+-------+----------------+------+-------------+-------------------+------------+------------+---------------+---------------+------------------+------------------+-----------------------------+----------+-----------------+-----------------------------------------------------------------------+
|game_id|competition_code|season|round        |date               |home_club_id|away_club_id|home_club_goals|away_club_goals|home_club_position|away_club_position|stadium                      |attendance|referee          |url                                                                    |
+-------+----------------+------+-------------+-------------------+------------+------------+---------------+---------------+------------------+------------------+-----------------------------+----------+-----------------+-----------------------------------------------------------------------+
|2457642|NLSC            |2014  |Final        |2014-08-03 00:00:00|1269        |610         |1              |0              |null              |null              |Johan Cruijff ArenA          |42000     |Danny Makkelie   |https://www.transfermarkt.co.uk/spielbericht/index/spielbericht/2457642|
|2639088|BESC            |2013  |Final        |2014-07-20 00:00:00|58          |498         |2              |1              |null              |null              |Constant Vanden Stock Stadion|13733     |Jonathan Lardot  |https://www.transfermarkt.co.uk/spielbericht/index/spielbericht/2639088|
|2481145|SUC             |2014  |final 1st leg|2014-08-19 00:00:00|418         |13          |1              |1              |null              |null              |Santiago Bernabéu            |75897     |Estrada Fernández|https://www.transfermarkt.co.uk/spielbericht/index/spielbericht/2481145|
|2484338|POSU            |2014  |Final        |2014-08-10 00:00:00|294         |2425        |3              |2              |null              |null              |Estádio Municipal de Aveiro  |30000     |Duarte Gomes     |https://www.transfermarkt.co.uk/spielbericht/index/spielbericht/2484338|
|2502472|FRCH            |2014  |Final        |2014-08-02 00:00:00|583         |855         |2              |0              |null              |null              |Workers Stadium              |39752     |Clément Turpin   |https://www.transfermarkt.co.uk/spielbericht/index/spielbericht/2502472|
+-------+----------------+------+-------------+-------------------+------------+------------+---------------+---------------+------------------+------------------+-----------------------------+----------+-----------------+-----------------------------------------------------------------------+
only showing top 5 rows

In [65]:
clubes.show(5, truncate=False)

+-------+-------------------+-------------------+-----------------------+------------------+----------+-----------+-----------------+---------------------+---------------------+--------------------------------------------+-------------+-------------------+----------------+--------------------------------------------------------------------------+
|club_id|name               |pretty_name        |domestic_competition_id|total_market_value|squad_size|average_age|foreigners_number|foreigners_percentage|national_team_players|stadium_name                                |stadium_seats|net_transfer_record|coach_name      |url                                                                       |
+-------+-------------------+-------------------+-----------------------+------------------+----------+-----------+-----------------+---------------------+---------------------+--------------------------------------------+-------------+-------------------+----------------+--------------------------------------------------------------------------+
|1429   |cesena-fc          |Cesena Fc          |IT1                    |5.09              |30        |24.0       |3                |10.0                 |1                    |"Orogel Stadium ""Dino Manuzzi"""           |23860        |+£180Th.           |Pierpaolo Bisoli|https://www.transfermarkt.co.uk/cesena-fc/startseite/verein/1429          |
|5220   |gs-ergotelis       |Gs Ergotelis       |GR1                    |3.62              |30        |22.7       |11               |36.7                 |1                    |Pankritio Stadio                            |25780        |+-0                |Juan Ferrando   |https://www.transfermarkt.co.uk/gs-ergotelis/startseite/verein/5220       |
|20698  |balikesirspor      |Balikesirspor      |TR1                    |2.21              |33        |25.5       |9                |27.3                 |1                    |Balıkesir Atatürk                           |15800        |+-0                |Ismail Ertekin  |https://www.transfermarkt.co.uk/balikesirspor/startseite/verein/20698     |
|6894   |kayseri-erciyesspor|Kayseri Erciyesspor|TR1                    |null              |0         |0.0        |0                |null                 |0                    |Kayseri Atatürk Spor Kompleksi Yan Açık Saha|2000         |+-0                |Hikmet Karaman  |https://www.transfermarkt.co.uk/kayseri-erciyesspor/startseite/verein/6894|
|5572   |niki-volou         |Niki Volou         |GR1                    |3.38              |26        |27.9       |6                |23.1                 |1                    |Panthessaliko Stadio                        |22700        |+-0                |Wiljan Vloet    |https://www.transfermarkt.co.uk/niki-volou/startseite/verein/5572         |
+-------+-------------------+-------------------+-----------------------+------------------+----------+-----------+-----------------+---------------------+---------------------+--------------------------------------------+-------------+-------------------+----------------+--------------------------------------------------------------------------+
only showing top 5 rows

In [66]:
jugadores.show(5, truncate=False)

+---------+---------------+-------------------+-------------------+----------------+----------------------+-------------------+----------+--------------+-----+------------+-------------------+---------------------------+------------------------------------------------------------------------+
|player_id|current_club_id|name               |pretty_name        |country_of_birth|country_of_citizenship|date_of_birth      |position  |sub_position  |foot |height_in_cm|market_value_in_gbp|highest_market_value_in_gbp|url                                                                     |
+---------+---------------+-------------------+-------------------+----------------+----------------------+-------------------+----------+--------------+-----+------------+-------------------+---------------------------+------------------------------------------------------------------------+
|38790    |28095          |dmitri-golubov     |Dmitri Golubov     |UdSSR           |Russia                |1985-06-24 00:00:00|Attack    |Centre-Forward|Both |178         |null               |675000.0                   |https://www.transfermarkt.co.uk/dmitri-golubov/profil/spieler/38790     |
|106539   |28095          |aleksandr-vasiljev |Aleksandr Vasiljev |Russia          |Russia                |1992-01-23 00:00:00|Attack    |Right Winger  |Right|182         |null               |225000.0                   |https://www.transfermarkt.co.uk/aleksandr-vasiljev/profil/spieler/106539|
|164389   |2288           |rory-donnelly      |Rory Donnelly      |Northern Ireland|Northern Ireland      |1992-02-18 00:00:00|Attack    |Centre-Forward|Right|188         |113000.0           |225000.0                   |https://www.transfermarkt.co.uk/rory-donnelly/profil/spieler/164389     |
|45247    |1162           |damien-perquis     |Damien Perquis     |France          |France                |1986-03-08 00:00:00|Goalkeeper|Goalkeeper    |Right|186         |null               |900000.0                   |https://www.transfermarkt.co.uk/damien-perquis/profil/spieler/45247     |
|97205    |28095          |nikita-bezlikhotnov|Nikita Bezlikhotnov|UdSSR           |Russia                |1990-08-19 00:00:00|Attack    |Right Winger  |Right|179         |null               |675000.0                   |https://www.transfermarkt.co.uk/nikita-bezlikhotnov/profil/spieler/97205|
+---------+---------------+-------------------+-------------------+----------------+----------------------+-------------------+----------+--------------+-----+------------+-------------------+---------------------------+------------------------------------------------------------------------+
only showing top 5 rows

In [69]:
apariciones.show(5, truncate=False)

+---------+-------+-------------+--------------+--------------+-----+-------+--------------+------------+---------+
|player_id|game_id|appearance_id|competition_id|player_club_id|goals|assists|minutes_played|yellow_cards|red_cards|
+---------+-------+-------------+--------------+--------------+-----+-------+--------------+------------+---------+
|52453    |2483937|2483937_52453|RU1           |28095         |0    |0      |90            |0           |0        |
|67064    |2479929|2479929_67064|RU1           |28095         |0    |0      |90            |0           |0        |
|67064    |2483937|2483937_67064|RU1           |28095         |0    |0      |90            |0           |0        |
|67064    |2484582|2484582_67064|RU1           |28095         |0    |0      |55            |0           |0        |
|67064    |2485965|2485965_67064|RU1           |28095         |0    |0      |90            |0           |0        |
+---------+-------+-------------+--------------+--------------+-----+-------+--------------+------------+---------+
only showing top 5 rows

In [162]:
competiciones.show(5, truncate=False)

+--------------+---------------+------------------+----------+------------+--------------------+-------------+-------------------------------------------------------------------------+
|competition_id|name           |type              |country_id|country_name|domestic_league_code|confederation|url                                                                      |
+--------------+---------------+------------------+----------+------------+--------------------+-------------+-------------------------------------------------------------------------+
|L1            |bundesliga     |first_tier        |40        |Germany     |L1                  |europa       |https://www.transfermarkt.co.uk/bundesliga/startseite/wettbewerb/L1      |
|DFB           |dfb-pokal      |domestic_cup      |40        |Germany     |L1                  |europa       |https://www.transfermarkt.co.uk/dfb-pokal/startseite/wettbewerb/DFB      |
|DFL           |dfl-supercup   |domestic_super_cup|40        |Germany     |L1                  |europa       |https://www.transfermarkt.co.uk/dfl-supercup/startseite/wettbewerb/DFL   |
|NL1           |eredivisie     |first_tier        |122       |Netherlands |NL1                 |europa       |https://www.transfermarkt.co.uk/eredivisie/startseite/wettbewerb/NL1     |
|NLP           |toto-knvb-beker|domestic_cup      |122       |Netherlands |NL1                 |europa       |https://www.transfermarkt.co.uk/toto-knvb-beker/startseite/wettbewerb/NLP|
+--------------+---------------+------------------+----------+------------+--------------------+-------------+-------------------------------------------------------------------------+
only showing top 5 rows

In [160]:
liga.show(10, truncate=False)

+---------+--------------------+-------------+
|league_id|name                |confederation|
+---------+--------------------+-------------+
|L1       |bundesliga          |europa       |
|NL1      |eredivisie          |europa       |
|BE1      |jupiler-pro-league  |europa       |
|ES1      |laliga              |europa       |
|PO1      |liga-nos            |europa       |
|FR1      |ligue-1             |europa       |
|GB1      |premier-league      |europa       |
|RU1      |premier-liga        |europa       |
|UKR1     |premier-liga        |europa       |
|SC1      |scottish-premiership|europa       |
+---------+--------------------+-------------+
only showing top 10 rows

1. Determine los tres países con mayor número de jugadores(jugadores nacidos en ese país). El resultado debe estar ordenado de forma descendente.

In [153]:
jugadores.filter(col('country_of_birth').isNotNull()).groupBy('country_of_birth').count().orderBy(desc('count')).limit(3).show()

+----------------+-----+
|country_of_birth|count|
+----------------+-----+
|          France| 1694|
|           Spain| 1388|
|           Italy| 1312|
+----------------+-----+

2. Obtenga la lista de jugadores con tarjeta roja. La salida debe contener dos columnas, el nombre de pila del jugador y la cantidad de tarjetas rojas que tiene.

In [159]:
df1 = jugadores.join(apariciones, ['player_id'], 'inner')
df2 = df1.filter(col('red_cards') > 0).select(col('pretty_name'), col('red_cards'))
df2.groupBy('pretty_name').count().orderBy(desc('count')).show()

+--------------------+-----+
|         pretty_name|count|
+--------------------+-----+
|             Marcelo|    6|
|     Mario Balotelli|    5|
|             Rodrigo|    5|
|              Hilton|    5|
|    Domenico Berardi|    5|
|        Granit Xhaka|    5|
|          Thomas Lam|    5|
|          Joao Pedro|    4|
|          David Luiz|    4|
|          Ante Rebic|    4|
|Timothee Kolodzie...|    4|
|      Rafik Halliche|    4|
|     Yannick Cahuzac|    4|
|     Damien Da Silva|    4|
|     Roberto Soriano|    4|
|     Rodrigo De Paul|    4|
|     Stefan Mitrovic|    4|
|   Kalidou Koulibaly|    4|
|       Ramon Leeuwin|    4|
|         Ivan Ordets|    4|
+--------------------+-----+
only showing top 20 rows

3. ¿Cuántos juegos se jugaron en la Premier League? La salida debe contener dos columnas, el nombre de la liga y la cantidad de juegos que se jugaron en ella.

In [163]:
data1 = juegos.join(competiciones, col('competition_id') == col('competition_code'), 'left')

In [164]:
data1.show()

+-------+----------------+------+-------------+-------------------+------------+------------+---------------+---------------+------------------+------------------+--------------------+----------+--------------------+--------------------+--------------+--------------------+------------------+----------+------------+--------------------+-------------+--------------------+
|game_id|competition_code|season|        round|               date|home_club_id|away_club_id|home_club_goals|away_club_goals|home_club_position|away_club_position|             stadium|attendance|             referee|                 url|competition_id|                name|              type|country_id|country_name|domestic_league_code|confederation|                 url|
+-------+----------------+------+-------------+-------------------+------------+------------+---------------+---------------+------------------+------------------+--------------------+----------+--------------------+--------------------+--------------+--------------------+------------------+----------+------------+--------------------+-------------+--------------------+
|2457642|            NLSC|  2014|        Final|2014-08-03 00:00:00|        1269|         610|              1|              0|              null|              null| Johan Cruijff ArenA|     42000|      Danny Makkelie|https://www.trans...|          NLSC|johan-cruijff-schaal|domestic_super_cup|       122| Netherlands|                 NL1|       europa|https://www.trans...|
|2639088|            BESC|  2013|        Final|2014-07-20 00:00:00|          58|         498|              2|              1|              null|              null|Constant Vanden S...|     13733|     Jonathan Lardot|https://www.trans...|          BESC|    belgian-supercup|domestic_super_cup|        19|     Belgium|                 BE1|       europa|https://www.trans...|
|2481145|             SUC|  2014|final 1st leg|2014-08-19 00:00:00|         418|          13|              1|              1|              null|              null|   Santiago Bernabéu|     75897|   Estrada Fernández|https://www.trans...|           SUC|           supercopa|domestic_super_cup|       157|       Spain|                 ES1|       europa|https://www.trans...|
|2484338|            POSU|  2014|        Final|2014-08-10 00:00:00|         294|        2425|              3|              2|              null|              null|Estádio Municipal...|     30000|        Duarte Gomes|https://www.trans...|          POSU|supertaca-candido...|domestic_super_cup|       136|    Portugal|                 PO1|       europa|https://www.trans...|
|2502472|            FRCH|  2014|        Final|2014-08-02 00:00:00|         583|         855|              2|              0|              null|              null|     Workers Stadium|     39752|      Clément Turpin|https://www.trans...|          FRCH|trophee-des-champ...|domestic_super_cup|        50|      France|                 FR1|       europa|https://www.trans...|
|2459774|             NL1|  2014| 21. Matchday|2015-02-05 00:00:00|         610|        1090|              0|              1|                 2|                 5| Johan Cruijff ArenA|     47724|      Pol van Boekel|https://www.trans...|           NL1|          eredivisie|        first_tier|       122| Netherlands|                 NL1|       europa|https://www.trans...|
|2480169|             PO1|  2014| 16. Matchday|2015-01-11 00:00:00|        2425|        1301|              0|              0|                 6|                10|   Estádio dos Arcos|      2230|       Tiago Martins|https://www.trans...|           PO1|  liga-portugal-bwin|        first_tier|       136|    Portugal|                 PO1|       europa|https://www.trans...|
|2490887|             PO1|  2014| 20. Matchday|2015-02-08 00:00:00|        1085|        2990|              0|              0|                14|                16|   Estádio do Bonfim|      3500|     Fábio Veríssimo|https://www.trans...|           PO1|  liga-portugal-bwin|        first_tier|       136|    Portugal|                 PO1|       europa|https://www.trans...|
|2498723|             PO1|  2014| 22. Matchday|2015-02-21 00:00:00|        1085|        3327|              0|              1|                15|                18|   Estádio do Bonfim|      2108|       Rui Rodrigues|https://www.trans...|           PO1|  liga-portugal-bwin|        first_tier|       136|    Portugal|                 PO1|       europa|https://www.trans...|
|2479542|            POCP|  2014|      Group C|2014-08-13 00:00:00|        3345|        4750|              0|              0|              null|              null|      Estádio do Mar|       448|       Jorge Tavares|https://www.trans...|          POCP|         allianz-cup|      domestic_cup|       136|    Portugal|                 PO1|       europa|https://www.trans...|
|2460640|              L1|  2014|  2. Matchday|2014-08-30 00:00:00|          86|         533|              1|              1|                 9|                 3|Wohninvest-Wesers...|     38900|     Robert Hartmann|https://www.trans...|            L1|          bundesliga|        first_tier|        40|     Germany|                  L1|       europa|https://www.trans...|
|2460300|             GB1|  2014|  1. Matchday|2014-08-16 00:00:00|         985|        2288|              1|              2|                15|                 5|        Old Trafford|     75339|           Mike Dean|https://www.trans...|           GB1|      premier-league|        first_tier|       189|     England|                 GB1|       europa|https://www.trans...|
|2486545|             GB1|  2014|  8. Matchday|2014-10-18 00:00:00|         180|         289|              8|              0|                 3|                17|   St Mary's Stadium|     29615|      Andre Marriner|https://www.trans...|           GB1|      premier-league|        first_tier|       189|     England|                 GB1|       europa|https://www.trans...|
|2486598|             GB1|  2014| 13. Matchday|2014-11-30 00:00:00|         148|          29|              2|              1|                 7|                10|     White Hart Lane|     35901|      Michael Oliver|https://www.trans...|           GB1|      premier-league|        first_tier|       189|     England|                 GB1|       europa|https://www.trans...|
|2486692|             GB1|  2014| 23. Matchday|2015-01-31 00:00:00|        3008|         762|              0|              3|                18|                11|        KCOM Stadium|     23925|           Phil Dowd|https://www.trans...|           GB1|      premier-league|        first_tier|       189|     England|                 GB1|       europa|https://www.trans...|
|2486714|             GB1|  2014| 25. Matchday|2015-02-10 00:00:00|          31|         148|              3|              2|                 7|                 6|             Anfield|     44577|           Phil Dowd|https://www.trans...|           GB1|      premier-league|        first_tier|       189|     England|                 GB1|       europa|https://www.trans...|
|2486726|             GB1|  2014| 26. Matchday|2015-02-21 00:00:00|         289|         984|              0|              0|                16|                14|    Stadium of Light|     40943|          Mike Jones|https://www.trans...|           GB1|      premier-league|        first_tier|       189|     England|                 GB1|       europa|https://www.trans...|
|2475235|             ES1|  2014|  6. Matchday|2014-09-26 00:00:00|        1531|         940|              0|              1|                18|                 6|Manuel Martínez V...|     20852|Pedro Jesús Pérez...|https://www.trans...|           ES1|              laliga|        first_tier|       157|       Spain|                 ES1|       europa|https://www.trans...|
|2475322|             ES1|  2014| 15. Matchday|2014-12-14 00:00:00|         681|         621|              1|              1|                14|                10|              Anoeta|     26651|David Fernández B...|https://www.trans...|           ES1|              laliga|        first_tier|       157|       Spain|                 ES1|       europa|https://www.trans...|
|2475350|             ES1|  2014| 18. Matchday|2015-01-10 00:00:00|        1084|        1050|              1|              1|                 7|                 6|         La Rosaleda|     22077|Santiago Jaime Latre|https://www.trans...|           ES1|              laliga|        first_tier|       157|       Spain|                 ES1|       europa|https://www.trans...|
+-------+----------------+------+-------------+-------------------+------------+------------+---------------+---------------+------------------+------------------+--------------------+----------+--------------------+--------------------+--------------+--------------------+------------------+----------+------------+--------------------+-------------+--------------------+
only showing top 20 rows

In [169]:
data1.groupBy('name').count().filter(col('name') == 'premier-league').show()

+--------------+-----+
|          name|count|
+--------------+-----+
|premier-league| 2809|
+--------------+-----+

4. Obtenga las tres ligas con mayor número de asistencia de público teniendo en cuenta todos los juegos que se jugaron en ellas. El resultado debe estar ordenado de forma descendente y tener dos columnas, el nombre de la liga y la asistencia total.

In [171]:
from pyspark.sql.functions import sum

In [172]:
data1.groupBy('name').agg(sum('attendance').alias('asistencia')).orderBy(desc('asistencia')).show()

+--------------------+----------+
|                name|asistencia|
+--------------------+----------+
|      premier-league|  86964852|
|          bundesliga|  78102473|
|              laliga|  62943533|
|             serie-a|  53475147|
|             ligue-1|  51593963|
|uefa-champions-le...|  35154225|
|          eredivisie|  34572418|
|       europa-league|  28710888|
|        premier-liga|  25823581|
|  liga-portugal-bwin|  20072843|
|  jupiler-pro-league|  17817099|
|           super-lig|  17455236|
|scottish-premiership|  17379753|
|europa-league-qua...|  12810167|
|uefa-champions-le...|   9479701|
|             efl-cup|   9162166|
|           dfb-pokal|   8404075|
|         superligaen|   7945555|
|        copa-del-rey|   7052640|
|      super-league-1|   6417136|
+--------------------+----------+
only showing top 20 rows